### ISSUE TITLE
Use User API to find fhem configuration files

### ISSUE THREAD

**Issue by nfarina** [cflurin/homebridge-fhem#1]
In response to this [Homebridge issue #379](https://github.com/nfarina/homebridge/issues/379), I added a new object to the `homebridge` API object for plugins called `user` which exposes methods to get the (now customizable) configuration path.

In [utils.js:13](https://github.com/cflurin/homebridge-fhem/blob/master/utils.js#L13), instead of using the pasted logic from homebridge to find the homebridge storage path, you can use this method on the API object:

    homebridge.user.storagePath()

There are some [other methods](https://github.com/nfarina/homebridge/blob/master/lib/user.js) on there as well.

**Comment by nfarina** [comment]
To avoid conflicts in the shared storage location, I would recommend storing your files in the location:

    path.join(homebridge.user.storagePath(), "plugins/homebridge-fhem/config-fhem.json")

**Comment by nfarina** [comment]
Also, your error message "Couldn't find config.json" should probably be tweaked :)

**Comment by cflurin** [comment]
@nfarina: Thanks for reporting. I was working on that (config.json > config-fhem.json).
I've modified utils.js in order to use homebridge.user.storagePaht(). I also put the config-fhem.json to the plugins/homebridge-fhem folder.

**Comment by nfarina** [comment]
Awesome!

**Comment by carnifex82** [comment]
Thanks for the quick fix!
